name: Check Translations

on: push

jobs:
  check-po:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install gettext utilities
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Check for untranslated entries
        run: ./scripts/i18n.sh
